apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: examples
  description: An example techdocs.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: user:guest
  lifecycle: experimental
